# Generated by Django 6.0.3 on 2026-04-07 21:57

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_company_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.company_logo_upload_path),
        ),
    ]
