# Generated by Django 6.0.3 on 2026-04-02 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_company_remove_customuser_roles_and_more'),
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategories',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('serial_number', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='assetassignment',
            unique_together={('asset', 'user')},
        ),
    ]
