# Generated by Django 6.0.3 on 2026-04-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_unique_together_assetimportsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetimportcolumnmapping',
            name='target_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assetimportsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
