# Generated by Django 6.0.3 on 2026-04-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_company_allow_join_request_company_is_listed_and_more'),
        ('assets', '0004_alter_assetimportcolumnmapping_target_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('serial_number', 'company')},
        ),
    ]
