# Generated by Django 6.0.3 on 2026-04-27 18:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_company_allow_join_request_company_is_listed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('ASSET_CREATED', 'Asset created'), ('ASSET_IMPORTED', 'Assets imported'), ('ASSET_ASSIGNED', 'Asset assigned'), ('ASSET_RECEIVED', 'Asset received'), ('ASSET_TRANSFERRED', 'Asset transferred'), ('JOIN_REQUEST_CREATED', 'Join request created'), ('JOIN_REQUEST_APPROVED', 'Join request approved'), ('JOIN_REQUEST_REJECTED', 'Join request rejected'), ('INVITE_CREATED', 'Invite created'), ('ORGANISATION_CREATED', 'Organisation created'), ('GENERAL', 'General')], default='GENERAL', max_length=50)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.company')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
